/**
 * Daily Initiative Engine v4 — 主动消息调度
 *
 * Standalone module for checking whether the character should
 * proactively send a message when the player has been idle.
 */

/**
 * Check if the character should send an initiative (proactive) message.
 *
 * @param {object} usk — USK snapshot (daily subspace)
 * @param {number} lastActiveTime — timestamp of player's last message
 * @param {number} lastInitiativeTime — timestamp of last initiative message
 * @returns {{ trigger: boolean, message?: string, delay?: number }}
 */
export function checkInitiative(usk, lastActiveTime, lastInitiativeTime = 0) {
  const now = Date.now()
  const idle = now - lastActiveTime
  const cooldown = now - lastInitiativeTime

  // Must be idle for at least 60 seconds
  if (idle < 60000) return { trigger: false }

  // Cooldown: at least 120 seconds between initiative messages
  if (cooldown < 120000) return { trigger: false }

  // Need minimum relationship (affection > 20) to bother reaching out
  const daily = usk?.daily || usk
  const affection = daily?.relationship ?? 50
  if (affection < 20) return { trigger: false }

  // Probability scales with idle time (max 30%)
  const probability = Math.min(idle / 600000, 0.3)
  if (Math.random() > probability) return { trigger: false }

  return {
    trigger: true,
    delay: 500 + Math.random() * 1500, // 0.5-2s delay
  }
}

/**
 * Get a pool of initiative message templates.
 * In production, these are generated by the LLM via sendDailyChatMessage
 * with a dedicated initiative system prompt.
 */
export const INITIATIVE_TEMPLATES = [
  '在干嘛',
  '刚看到个东西想起你了',
  '[表情包]',
  '睡了没',
  '…算了没事',
  '你今天好像没怎么说话',
]

/**
 * Pick a random initiative template.
 */
export function pickInitiativeTemplate() {
  return INITIATIVE_TEMPLATES[Math.floor(Math.random() * INITIATIVE_TEMPLATES.length)]
}
